# Generated by Django 5.2.1 on 2025-05-26 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop_admin", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ShopAdmin",
            new_name="ShopAdminDjango",
        ),
    ]
