# Generated by Django 5.2.1 on 2025-05-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "discount_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("discount", models.CharField(blank=True, max_length=10, null=True)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("reviews", models.IntegerField(blank=True, null=True)),
                ("stock", models.IntegerField()),
                ("category", models.CharField(max_length=255)),
                ("brand", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("images", models.JSONField(default=list)),
                ("features", models.JSONField(default=list)),
                ("specifications", models.JSONField(default=dict)),
            ],
        ),
    ]
