# Generated by Django 5.2.1 on 2025-05-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_cart_order_orderitem_cartitem_wishlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="variant",
            field=models.JSONField(default=dict),
        ),
    ]
